# coding: utf-8

"""
    GoPlus Security API Document

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class AbiParamInfo(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'address_info': 'AbiAddressInfo',
        'input': 'object',
        'name': 'str',
        'type': 'str'
    }

    attribute_map = {
        'address_info': 'address_info',
        'input': 'input',
        'name': 'name',
        'type': 'type'
    }

    def __init__(self, address_info=None, input=None, name=None, type=None):  # noqa: E501
        """AbiParamInfo - a model defined in Swagger"""  # noqa: E501
        self._address_info = None
        self._input = None
        self._name = None
        self._type = None
        self.discriminator = None
        if address_info is not None:
            self.address_info = address_info
        if input is not None:
            self.input = input
        if name is not None:
            self.name = name
        if type is not None:
            self.type = type

    @property
    def address_info(self):
        """Gets the address_info of this AbiParamInfo.  # noqa: E501


        :return: The address_info of this AbiParamInfo.  # noqa: E501
        :rtype: AbiAddressInfo
        """
        return self._address_info

    @address_info.setter
    def address_info(self, address_info):
        """Sets the address_info of this AbiParamInfo.


        :param address_info: The address_info of this AbiParamInfo.  # noqa: E501
        :type: AbiAddressInfo
        """

        self._address_info = address_info

    @property
    def input(self):
        """Gets the input of this AbiParamInfo.  # noqa: E501

        It describes the input data in ABI.  # noqa: E501

        :return: The input of this AbiParamInfo.  # noqa: E501
        :rtype: object
        """
        return self._input

    @input.setter
    def input(self, input):
        """Sets the input of this AbiParamInfo.

        It describes the input data in ABI.  # noqa: E501

        :param input: The input of this AbiParamInfo.  # noqa: E501
        :type: object
        """

        self._input = input

    @property
    def name(self):
        """Gets the name of this AbiParamInfo.  # noqa: E501

        It describes the parameter name in ABI, for example   \"_from\", \"_to\", \"_value\".  # noqa: E501

        :return: The name of this AbiParamInfo.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this AbiParamInfo.

        It describes the parameter name in ABI, for example   \"_from\", \"_to\", \"_value\".  # noqa: E501

        :param name: The name of this AbiParamInfo.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def type(self):
        """Gets the type of this AbiParamInfo.  # noqa: E501

        It describes the parameter type in ABI, for example \"address\", \"uint256\", \"bool\".  # noqa: E501

        :return: The type of this AbiParamInfo.  # noqa: E501
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this AbiParamInfo.

        It describes the parameter type in ABI, for example \"address\", \"uint256\", \"bool\".  # noqa: E501

        :param type: The type of this AbiParamInfo.  # noqa: E501
        :type: str
        """

        self._type = type

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(AbiParamInfo, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, AbiParamInfo):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
