# coding: utf-8

"""
    GoPlus Security API Document

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class AllowanceChange(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'amount': 'str',
        'contract_address': 'str',
        'owner': 'str',
        'spender': 'str'
    }

    attribute_map = {
        'amount': 'amount',
        'contract_address': 'contract_address',
        'owner': 'owner',
        'spender': 'spender'
    }

    def __init__(self, amount=None, contract_address=None, owner=None, spender=None):  # noqa: E501
        """AllowanceChange - a model defined in Swagger"""  # noqa: E501
        self._amount = None
        self._contract_address = None
        self._owner = None
        self._spender = None
        self.discriminator = None
        if amount is not None:
            self.amount = amount
        if contract_address is not None:
            self.contract_address = contract_address
        if owner is not None:
            self.owner = owner
        if spender is not None:
            self.spender = spender

    @property
    def amount(self):
        """Gets the amount of this AllowanceChange.  # noqa: E501


        :return: The amount of this AllowanceChange.  # noqa: E501
        :rtype: str
        """
        return self._amount

    @amount.setter
    def amount(self, amount):
        """Sets the amount of this AllowanceChange.


        :param amount: The amount of this AllowanceChange.  # noqa: E501
        :type: str
        """

        self._amount = amount

    @property
    def contract_address(self):
        """Gets the contract_address of this AllowanceChange.  # noqa: E501


        :return: The contract_address of this AllowanceChange.  # noqa: E501
        :rtype: str
        """
        return self._contract_address

    @contract_address.setter
    def contract_address(self, contract_address):
        """Sets the contract_address of this AllowanceChange.


        :param contract_address: The contract_address of this AllowanceChange.  # noqa: E501
        :type: str
        """

        self._contract_address = contract_address

    @property
    def owner(self):
        """Gets the owner of this AllowanceChange.  # noqa: E501


        :return: The owner of this AllowanceChange.  # noqa: E501
        :rtype: str
        """
        return self._owner

    @owner.setter
    def owner(self, owner):
        """Sets the owner of this AllowanceChange.


        :param owner: The owner of this AllowanceChange.  # noqa: E501
        :type: str
        """

        self._owner = owner

    @property
    def spender(self):
        """Gets the spender of this AllowanceChange.  # noqa: E501


        :return: The spender of this AllowanceChange.  # noqa: E501
        :rtype: str
        """
        return self._spender

    @spender.setter
    def spender(self, spender):
        """Sets the spender of this AllowanceChange.


        :param spender: The spender of this AllowanceChange.  # noqa: E501
        :type: str
        """

        self._spender = spender

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(AllowanceChange, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, AllowanceChange):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
