# coding: utf-8

"""
    GoPlus Security API Documentation

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class ContractsSecurity(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'chain_id': 'str',
        'contracts': 'list[Contracts]'
    }

    attribute_map = {
        'chain_id': 'chain_id',
        'contracts': 'contracts'
    }

    def __init__(self, chain_id=None, contracts=None):  # noqa: E501
        """ContractsSecurity - a model defined in Swagger"""  # noqa: E501
        self._chain_id = None
        self._contracts = None
        self.discriminator = None
        if chain_id is not None:
            self.chain_id = chain_id
        if contracts is not None:
            self.contracts = contracts

    @property
    def chain_id(self):
        """Gets the chain_id of this ContractsSecurity.  # noqa: E501

        It describes the chains that contracts are deployed on;\"1\" means Ethereum; \"25\" means Cronos; \"56\" means BSC; \"128\" means HECO; \"137\" means Polygon; \"250\" means Fantom; \"42161\" means Arbitrum; \"43114\" means Avalanche.  # noqa: E501

        :return: The chain_id of this ContractsSecurity.  # noqa: E501
        :rtype: str
        """
        return self._chain_id

    @chain_id.setter
    def chain_id(self, chain_id):
        """Sets the chain_id of this ContractsSecurity.

        It describes the chains that contracts are deployed on;\"1\" means Ethereum; \"25\" means Cronos; \"56\" means BSC; \"128\" means HECO; \"137\" means Polygon; \"250\" means Fantom; \"42161\" means Arbitrum; \"43114\" means Avalanche.  # noqa: E501

        :param chain_id: The chain_id of this ContractsSecurity.  # noqa: E501
        :type: str
        """

        self._chain_id = chain_id

    @property
    def contracts(self):
        """Gets the contracts of this ContractsSecurity.  # noqa: E501

        contract info  # noqa: E501

        :return: The contracts of this ContractsSecurity.  # noqa: E501
        :rtype: list[Contracts]
        """
        return self._contracts

    @contracts.setter
    def contracts(self, contracts):
        """Sets the contracts of this ContractsSecurity.

        contract info  # noqa: E501

        :param contracts: The contracts of this ContractsSecurity.  # noqa: E501
        :type: list[Contracts]
        """

        self._contracts = contracts

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ContractsSecurity, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ContractsSecurity):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
