# coding: utf-8

"""
    GoPlus Security API Document

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class ERC721Change(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'received': 'bool',
        'token_address': 'str',
        'token_id': 'str'
    }

    attribute_map = {
        'received': 'received',
        'token_address': 'token_address',
        'token_id': 'token_id'
    }

    def __init__(self, received=None, token_address=None, token_id=None):  # noqa: E501
        """ERC721Change - a model defined in Swagger"""  # noqa: E501
        self._received = None
        self._token_address = None
        self._token_id = None
        self.discriminator = None
        if received is not None:
            self.received = received
        if token_address is not None:
            self.token_address = token_address
        if token_id is not None:
            self.token_id = token_id

    @property
    def received(self):
        """Gets the received of this ERC721Change.  # noqa: E501


        :return: The received of this ERC721Change.  # noqa: E501
        :rtype: bool
        """
        return self._received

    @received.setter
    def received(self, received):
        """Sets the received of this ERC721Change.


        :param received: The received of this ERC721Change.  # noqa: E501
        :type: bool
        """

        self._received = received

    @property
    def token_address(self):
        """Gets the token_address of this ERC721Change.  # noqa: E501


        :return: The token_address of this ERC721Change.  # noqa: E501
        :rtype: str
        """
        return self._token_address

    @token_address.setter
    def token_address(self, token_address):
        """Sets the token_address of this ERC721Change.


        :param token_address: The token_address of this ERC721Change.  # noqa: E501
        :type: str
        """

        self._token_address = token_address

    @property
    def token_id(self):
        """Gets the token_id of this ERC721Change.  # noqa: E501


        :return: The token_id of this ERC721Change.  # noqa: E501
        :rtype: str
        """
        return self._token_id

    @token_id.setter
    def token_id(self, token_id):
        """Sets the token_id of this ERC721Change.


        :param token_id: The token_id of this ERC721Change.  # noqa: E501
        :type: str
        """

        self._token_id = token_id

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ERC721Change, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ERC721Change):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
