# coding: utf-8

"""
    GoPlus Security API Document

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class NativeChange(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'after': 'str',
        'before': 'str',
        'change': 'str'
    }

    attribute_map = {
        'after': 'after',
        'before': 'before',
        'change': 'change'
    }

    def __init__(self, after=None, before=None, change=None):  # noqa: E501
        """NativeChange - a model defined in Swagger"""  # noqa: E501
        self._after = None
        self._before = None
        self._change = None
        self.discriminator = None
        if after is not None:
            self.after = after
        if before is not None:
            self.before = before
        if change is not None:
            self.change = change

    @property
    def after(self):
        """Gets the after of this NativeChange.  # noqa: E501


        :return: The after of this NativeChange.  # noqa: E501
        :rtype: str
        """
        return self._after

    @after.setter
    def after(self, after):
        """Sets the after of this NativeChange.


        :param after: The after of this NativeChange.  # noqa: E501
        :type: str
        """

        self._after = after

    @property
    def before(self):
        """Gets the before of this NativeChange.  # noqa: E501


        :return: The before of this NativeChange.  # noqa: E501
        :rtype: str
        """
        return self._before

    @before.setter
    def before(self, before):
        """Sets the before of this NativeChange.


        :param before: The before of this NativeChange.  # noqa: E501
        :type: str
        """

        self._before = before

    @property
    def change(self):
        """Gets the change of this NativeChange.  # noqa: E501


        :return: The change of this NativeChange.  # noqa: E501
        :rtype: str
        """
        return self._change

    @change.setter
    def change(self, change):
        """Sets the change of this NativeChange.


        :param change: The change of this NativeChange.  # noqa: E501
        :type: str
        """

        self._change = change

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(NativeChange, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, NativeChange):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
