# coding: utf-8

"""
    GoPlus Security API Document

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class ResponseWrapperSolanaTokenSecurityTransferFee(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'scheduled_fee_rate': 'list[ResponseWrapperSolanaTokenSecurityTransferFeeScheduledFeeRate]',
        'current_fee_rate': 'ResponseWrapperSolanaTokenSecurityTransferFeeCurrentFeeRate'
    }

    attribute_map = {
        'scheduled_fee_rate': 'scheduled_fee_rate',
        'current_fee_rate': 'current_fee_rate'
    }

    def __init__(self, scheduled_fee_rate=None, current_fee_rate=None):  # noqa: E501
        """ResponseWrapperSolanaTokenSecurityTransferFee - a model defined in Swagger"""  # noqa: E501
        self._scheduled_fee_rate = None
        self._current_fee_rate = None
        self.discriminator = None
        if scheduled_fee_rate is not None:
            self.scheduled_fee_rate = scheduled_fee_rate
        if current_fee_rate is not None:
            self.current_fee_rate = current_fee_rate

    @property
    def scheduled_fee_rate(self):
        """Gets the scheduled_fee_rate of this ResponseWrapperSolanaTokenSecurityTransferFee.  # noqa: E501

        Scheduled changes to transfer fee rates.  # noqa: E501

        :return: The scheduled_fee_rate of this ResponseWrapperSolanaTokenSecurityTransferFee.  # noqa: E501
        :rtype: list[ResponseWrapperSolanaTokenSecurityTransferFeeScheduledFeeRate]
        """
        return self._scheduled_fee_rate

    @scheduled_fee_rate.setter
    def scheduled_fee_rate(self, scheduled_fee_rate):
        """Sets the scheduled_fee_rate of this ResponseWrapperSolanaTokenSecurityTransferFee.

        Scheduled changes to transfer fee rates.  # noqa: E501

        :param scheduled_fee_rate: The scheduled_fee_rate of this ResponseWrapperSolanaTokenSecurityTransferFee.  # noqa: E501
        :type: list[ResponseWrapperSolanaTokenSecurityTransferFeeScheduledFeeRate]
        """

        self._scheduled_fee_rate = scheduled_fee_rate

    @property
    def current_fee_rate(self):
        """Gets the current_fee_rate of this ResponseWrapperSolanaTokenSecurityTransferFee.  # noqa: E501


        :return: The current_fee_rate of this ResponseWrapperSolanaTokenSecurityTransferFee.  # noqa: E501
        :rtype: ResponseWrapperSolanaTokenSecurityTransferFeeCurrentFeeRate
        """
        return self._current_fee_rate

    @current_fee_rate.setter
    def current_fee_rate(self, current_fee_rate):
        """Sets the current_fee_rate of this ResponseWrapperSolanaTokenSecurityTransferFee.


        :param current_fee_rate: The current_fee_rate of this ResponseWrapperSolanaTokenSecurityTransferFee.  # noqa: E501
        :type: ResponseWrapperSolanaTokenSecurityTransferFeeCurrentFeeRate
        """

        self._current_fee_rate = current_fee_rate

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ResponseWrapperSolanaTokenSecurityTransferFee, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ResponseWrapperSolanaTokenSecurityTransferFee):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
