# coding: utf-8

"""
    GoPlus Security API Document

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class ResponseWrapperSolanaTokenSecurityMetadataMutable(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'metadata_upgrade_authority': 'list[ResponseWrapperSolanaTokenSecurityClosableAuthority]',
        'status': 'str'
    }

    attribute_map = {
        'metadata_upgrade_authority': 'metadata_upgrade_authority',
        'status': 'status'
    }

    def __init__(self, metadata_upgrade_authority=None, status=None):  # noqa: E501
        """ResponseWrapperSolanaTokenSecurityMetadataMutable - a model defined in Swagger"""  # noqa: E501
        self._metadata_upgrade_authority = None
        self._status = None
        self.discriminator = None
        if metadata_upgrade_authority is not None:
            self.metadata_upgrade_authority = metadata_upgrade_authority
        if status is not None:
            self.status = status

    @property
    def metadata_upgrade_authority(self):
        """Gets the metadata_upgrade_authority of this ResponseWrapperSolanaTokenSecurityMetadataMutable.  # noqa: E501

        Information on metadata upgrade authority.  # noqa: E501

        :return: The metadata_upgrade_authority of this ResponseWrapperSolanaTokenSecurityMetadataMutable.  # noqa: E501
        :rtype: list[ResponseWrapperSolanaTokenSecurityClosableAuthority]
        """
        return self._metadata_upgrade_authority

    @metadata_upgrade_authority.setter
    def metadata_upgrade_authority(self, metadata_upgrade_authority):
        """Sets the metadata_upgrade_authority of this ResponseWrapperSolanaTokenSecurityMetadataMutable.

        Information on metadata upgrade authority.  # noqa: E501

        :param metadata_upgrade_authority: The metadata_upgrade_authority of this ResponseWrapperSolanaTokenSecurityMetadataMutable.  # noqa: E501
        :type: list[ResponseWrapperSolanaTokenSecurityClosableAuthority]
        """

        self._metadata_upgrade_authority = metadata_upgrade_authority

    @property
    def status(self):
        """Gets the status of this ResponseWrapperSolanaTokenSecurityMetadataMutable.  # noqa: E501

        Status indicator, where \"1\" means the funtcion is available.  # noqa: E501

        :return: The status of this ResponseWrapperSolanaTokenSecurityMetadataMutable.  # noqa: E501
        :rtype: str
        """
        return self._status

    @status.setter
    def status(self, status):
        """Sets the status of this ResponseWrapperSolanaTokenSecurityMetadataMutable.

        Status indicator, where \"1\" means the funtcion is available.  # noqa: E501

        :param status: The status of this ResponseWrapperSolanaTokenSecurityMetadataMutable.  # noqa: E501
        :type: str
        """

        self._status = status

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ResponseWrapperSolanaTokenSecurityMetadataMutable, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ResponseWrapperSolanaTokenSecurityMetadataMutable):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
