# coding: utf-8

"""
    GoPlus Security API Document

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class ResponseWrapperTokenSecurityB20TokenB20Info(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'transfer_pausable': 'ResponseWrapperTokenSecurityB20TokenB20InfoTransferPausable',
        'owner_change_balance': 'ResponseWrapperTokenSecurityB20TokenB20InfoOwnerChangeBalance',
        'cannot_buy': 'ResponseWrapperTokenSecurityB20TokenB20InfoCannotBuy',
        'metadata_modifiable': 'ResponseWrapperTokenSecurityB20TokenB20InfoMetadataModifiable',
        'blacklist': 'ResponseWrapperTokenSecurityB20TokenB20InfoBlacklist',
        'cannot_sell': 'ResponseWrapperTokenSecurityB20TokenB20InfoCannotSell',
        'whitelist': 'ResponseWrapperTokenSecurityB20TokenB20InfoWhitelist',
        'mintable': 'ResponseWrapperTokenSecurityB20TokenB20InfoMintable'
    }

    attribute_map = {
        'transfer_pausable': 'transfer_pausable',
        'owner_change_balance': 'owner_change_balance',
        'cannot_buy': 'cannot_buy',
        'metadata_modifiable': 'metadata_modifiable',
        'blacklist': 'blacklist',
        'cannot_sell': 'cannot_sell',
        'whitelist': 'whitelist',
        'mintable': 'mintable'
    }

    def __init__(self, transfer_pausable=None, owner_change_balance=None, cannot_buy=None, metadata_modifiable=None, blacklist=None, cannot_sell=None, whitelist=None, mintable=None):  # noqa: E501
        """ResponseWrapperTokenSecurityB20TokenB20Info - a model defined in Swagger"""  # noqa: E501
        self._transfer_pausable = None
        self._owner_change_balance = None
        self._cannot_buy = None
        self._metadata_modifiable = None
        self._blacklist = None
        self._cannot_sell = None
        self._whitelist = None
        self._mintable = None
        self.discriminator = None
        if transfer_pausable is not None:
            self.transfer_pausable = transfer_pausable
        if owner_change_balance is not None:
            self.owner_change_balance = owner_change_balance
        if cannot_buy is not None:
            self.cannot_buy = cannot_buy
        if metadata_modifiable is not None:
            self.metadata_modifiable = metadata_modifiable
        if blacklist is not None:
            self.blacklist = blacklist
        if cannot_sell is not None:
            self.cannot_sell = cannot_sell
        if whitelist is not None:
            self.whitelist = whitelist
        if mintable is not None:
            self.mintable = mintable

    @property
    def transfer_pausable(self):
        """Gets the transfer_pausable of this ResponseWrapperTokenSecurityB20TokenB20Info.  # noqa: E501


        :return: The transfer_pausable of this ResponseWrapperTokenSecurityB20TokenB20Info.  # noqa: E501
        :rtype: ResponseWrapperTokenSecurityB20TokenB20InfoTransferPausable
        """
        return self._transfer_pausable

    @transfer_pausable.setter
    def transfer_pausable(self, transfer_pausable):
        """Sets the transfer_pausable of this ResponseWrapperTokenSecurityB20TokenB20Info.


        :param transfer_pausable: The transfer_pausable of this ResponseWrapperTokenSecurityB20TokenB20Info.  # noqa: E501
        :type: ResponseWrapperTokenSecurityB20TokenB20InfoTransferPausable
        """

        self._transfer_pausable = transfer_pausable

    @property
    def owner_change_balance(self):
        """Gets the owner_change_balance of this ResponseWrapperTokenSecurityB20TokenB20Info.  # noqa: E501


        :return: The owner_change_balance of this ResponseWrapperTokenSecurityB20TokenB20Info.  # noqa: E501
        :rtype: ResponseWrapperTokenSecurityB20TokenB20InfoOwnerChangeBalance
        """
        return self._owner_change_balance

    @owner_change_balance.setter
    def owner_change_balance(self, owner_change_balance):
        """Sets the owner_change_balance of this ResponseWrapperTokenSecurityB20TokenB20Info.


        :param owner_change_balance: The owner_change_balance of this ResponseWrapperTokenSecurityB20TokenB20Info.  # noqa: E501
        :type: ResponseWrapperTokenSecurityB20TokenB20InfoOwnerChangeBalance
        """

        self._owner_change_balance = owner_change_balance

    @property
    def cannot_buy(self):
        """Gets the cannot_buy of this ResponseWrapperTokenSecurityB20TokenB20Info.  # noqa: E501


        :return: The cannot_buy of this ResponseWrapperTokenSecurityB20TokenB20Info.  # noqa: E501
        :rtype: ResponseWrapperTokenSecurityB20TokenB20InfoCannotBuy
        """
        return self._cannot_buy

    @cannot_buy.setter
    def cannot_buy(self, cannot_buy):
        """Sets the cannot_buy of this ResponseWrapperTokenSecurityB20TokenB20Info.


        :param cannot_buy: The cannot_buy of this ResponseWrapperTokenSecurityB20TokenB20Info.  # noqa: E501
        :type: ResponseWrapperTokenSecurityB20TokenB20InfoCannotBuy
        """

        self._cannot_buy = cannot_buy

    @property
    def metadata_modifiable(self):
        """Gets the metadata_modifiable of this ResponseWrapperTokenSecurityB20TokenB20Info.  # noqa: E501


        :return: The metadata_modifiable of this ResponseWrapperTokenSecurityB20TokenB20Info.  # noqa: E501
        :rtype: ResponseWrapperTokenSecurityB20TokenB20InfoMetadataModifiable
        """
        return self._metadata_modifiable

    @metadata_modifiable.setter
    def metadata_modifiable(self, metadata_modifiable):
        """Sets the metadata_modifiable of this ResponseWrapperTokenSecurityB20TokenB20Info.


        :param metadata_modifiable: The metadata_modifiable of this ResponseWrapperTokenSecurityB20TokenB20Info.  # noqa: E501
        :type: ResponseWrapperTokenSecurityB20TokenB20InfoMetadataModifiable
        """

        self._metadata_modifiable = metadata_modifiable

    @property
    def blacklist(self):
        """Gets the blacklist of this ResponseWrapperTokenSecurityB20TokenB20Info.  # noqa: E501


        :return: The blacklist of this ResponseWrapperTokenSecurityB20TokenB20Info.  # noqa: E501
        :rtype: ResponseWrapperTokenSecurityB20TokenB20InfoBlacklist
        """
        return self._blacklist

    @blacklist.setter
    def blacklist(self, blacklist):
        """Sets the blacklist of this ResponseWrapperTokenSecurityB20TokenB20Info.


        :param blacklist: The blacklist of this ResponseWrapperTokenSecurityB20TokenB20Info.  # noqa: E501
        :type: ResponseWrapperTokenSecurityB20TokenB20InfoBlacklist
        """

        self._blacklist = blacklist

    @property
    def cannot_sell(self):
        """Gets the cannot_sell of this ResponseWrapperTokenSecurityB20TokenB20Info.  # noqa: E501


        :return: The cannot_sell of this ResponseWrapperTokenSecurityB20TokenB20Info.  # noqa: E501
        :rtype: ResponseWrapperTokenSecurityB20TokenB20InfoCannotSell
        """
        return self._cannot_sell

    @cannot_sell.setter
    def cannot_sell(self, cannot_sell):
        """Sets the cannot_sell of this ResponseWrapperTokenSecurityB20TokenB20Info.


        :param cannot_sell: The cannot_sell of this ResponseWrapperTokenSecurityB20TokenB20Info.  # noqa: E501
        :type: ResponseWrapperTokenSecurityB20TokenB20InfoCannotSell
        """

        self._cannot_sell = cannot_sell

    @property
    def whitelist(self):
        """Gets the whitelist of this ResponseWrapperTokenSecurityB20TokenB20Info.  # noqa: E501


        :return: The whitelist of this ResponseWrapperTokenSecurityB20TokenB20Info.  # noqa: E501
        :rtype: ResponseWrapperTokenSecurityB20TokenB20InfoWhitelist
        """
        return self._whitelist

    @whitelist.setter
    def whitelist(self, whitelist):
        """Sets the whitelist of this ResponseWrapperTokenSecurityB20TokenB20Info.


        :param whitelist: The whitelist of this ResponseWrapperTokenSecurityB20TokenB20Info.  # noqa: E501
        :type: ResponseWrapperTokenSecurityB20TokenB20InfoWhitelist
        """

        self._whitelist = whitelist

    @property
    def mintable(self):
        """Gets the mintable of this ResponseWrapperTokenSecurityB20TokenB20Info.  # noqa: E501


        :return: The mintable of this ResponseWrapperTokenSecurityB20TokenB20Info.  # noqa: E501
        :rtype: ResponseWrapperTokenSecurityB20TokenB20InfoMintable
        """
        return self._mintable

    @mintable.setter
    def mintable(self, mintable):
        """Sets the mintable of this ResponseWrapperTokenSecurityB20TokenB20Info.


        :param mintable: The mintable of this ResponseWrapperTokenSecurityB20TokenB20Info.  # noqa: E501
        :type: ResponseWrapperTokenSecurityB20TokenB20InfoMintable
        """

        self._mintable = mintable

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ResponseWrapperTokenSecurityB20TokenB20Info, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ResponseWrapperTokenSecurityB20TokenB20Info):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
