# coding: utf-8

"""
    GoPlus Security API Document

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class ResponseWrapperTokenSecurityB20TokenB20InfoCannotBuy(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'admin': 'list[str]',
        'status': 'str'
    }

    attribute_map = {
        'admin': 'admin',
        'status': 'status'
    }

    def __init__(self, admin=None, status=None):  # noqa: E501
        """ResponseWrapperTokenSecurityB20TokenB20InfoCannotBuy - a model defined in Swagger"""  # noqa: E501
        self._admin = None
        self._status = None
        self.discriminator = None
        if admin is not None:
            self.admin = admin
        if status is not None:
            self.status = status

    @property
    def admin(self):
        """Gets the admin of this ResponseWrapperTokenSecurityB20TokenB20InfoCannotBuy.  # noqa: E501

        It describes the admin addresses who have the cannot_buy permission.  Example: []  # noqa: E501

        :return: The admin of this ResponseWrapperTokenSecurityB20TokenB20InfoCannotBuy.  # noqa: E501
        :rtype: list[str]
        """
        return self._admin

    @admin.setter
    def admin(self, admin):
        """Sets the admin of this ResponseWrapperTokenSecurityB20TokenB20InfoCannotBuy.

        It describes the admin addresses who have the cannot_buy permission.  Example: []  # noqa: E501

        :param admin: The admin of this ResponseWrapperTokenSecurityB20TokenB20InfoCannotBuy.  # noqa: E501
        :type: list[str]
        """

        self._admin = admin

    @property
    def status(self):
        """Gets the status of this ResponseWrapperTokenSecurityB20TokenB20InfoCannotBuy.  # noqa: E501

        It describes whether the cannot_buy permission is enabled.  \"1\" means enabled;  \"0\" means disabled;  # noqa: E501

        :return: The status of this ResponseWrapperTokenSecurityB20TokenB20InfoCannotBuy.  # noqa: E501
        :rtype: str
        """
        return self._status

    @status.setter
    def status(self, status):
        """Sets the status of this ResponseWrapperTokenSecurityB20TokenB20InfoCannotBuy.

        It describes whether the cannot_buy permission is enabled.  \"1\" means enabled;  \"0\" means disabled;  # noqa: E501

        :param status: The status of this ResponseWrapperTokenSecurityB20TokenB20InfoCannotBuy.  # noqa: E501
        :type: str
        """

        self._status = status

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ResponseWrapperTokenSecurityB20TokenB20InfoCannotBuy, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ResponseWrapperTokenSecurityB20TokenB20InfoCannotBuy):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
