# coding: utf-8

"""
    GoPlus Security API Document

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class ResponseWrapperTokenSecurityLockedDetail(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'amount': 'str',
        'opt_time': 'str',
        'end_time': 'str'
    }

    attribute_map = {
        'amount': 'amount',
        'opt_time': 'opt_time',
        'end_time': 'end_time'
    }

    def __init__(self, amount=None, opt_time=None, end_time=None):  # noqa: E501
        """ResponseWrapperTokenSecurityLockedDetail - a model defined in Swagger"""  # noqa: E501
        self._amount = None
        self._opt_time = None
        self._end_time = None
        self.discriminator = None
        if amount is not None:
            self.amount = amount
        if opt_time is not None:
            self.opt_time = opt_time
        if end_time is not None:
            self.end_time = end_time

    @property
    def amount(self):
        """Gets the amount of this ResponseWrapperTokenSecurityLockedDetail.  # noqa: E501

        \"amount\" describes the number of token locked  # noqa: E501

        :return: The amount of this ResponseWrapperTokenSecurityLockedDetail.  # noqa: E501
        :rtype: str
        """
        return self._amount

    @amount.setter
    def amount(self, amount):
        """Sets the amount of this ResponseWrapperTokenSecurityLockedDetail.

        \"amount\" describes the number of token locked  # noqa: E501

        :param amount: The amount of this ResponseWrapperTokenSecurityLockedDetail.  # noqa: E501
        :type: str
        """

        self._amount = amount

    @property
    def opt_time(self):
        """Gets the opt_time of this ResponseWrapperTokenSecurityLockedDetail.  # noqa: E501

        \"opt_time\" describes when the token was locked  # noqa: E501

        :return: The opt_time of this ResponseWrapperTokenSecurityLockedDetail.  # noqa: E501
        :rtype: str
        """
        return self._opt_time

    @opt_time.setter
    def opt_time(self, opt_time):
        """Sets the opt_time of this ResponseWrapperTokenSecurityLockedDetail.

        \"opt_time\" describes when the token was locked  # noqa: E501

        :param opt_time: The opt_time of this ResponseWrapperTokenSecurityLockedDetail.  # noqa: E501
        :type: str
        """

        self._opt_time = opt_time

    @property
    def end_time(self):
        """Gets the end_time of this ResponseWrapperTokenSecurityLockedDetail.  # noqa: E501

        \"end_time\" describes when the token will be unlocked  # noqa: E501

        :return: The end_time of this ResponseWrapperTokenSecurityLockedDetail.  # noqa: E501
        :rtype: str
        """
        return self._end_time

    @end_time.setter
    def end_time(self, end_time):
        """Sets the end_time of this ResponseWrapperTokenSecurityLockedDetail.

        \"end_time\" describes when the token will be unlocked  # noqa: E501

        :param end_time: The end_time of this ResponseWrapperTokenSecurityLockedDetail.  # noqa: E501
        :type: str
        """

        self._end_time = end_time

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ResponseWrapperTokenSecurityLockedDetail, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ResponseWrapperTokenSecurityLockedDetail):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
