# coding: utf-8

"""
    GoPlus Security API Document

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class ResponseWrapperTokenSecurityB20Token(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'is_b20_token': 'str',
        'b20_info': 'ResponseWrapperTokenSecurityB20TokenB20Info'
    }

    attribute_map = {
        'is_b20_token': 'is_b20_token',
        'b20_info': 'b20_info'
    }

    def __init__(self, is_b20_token=None, b20_info=None):  # noqa: E501
        """ResponseWrapperTokenSecurityB20Token - a model defined in Swagger"""  # noqa: E501
        self._is_b20_token = None
        self._b20_info = None
        self.discriminator = None
        if is_b20_token is not None:
            self.is_b20_token = is_b20_token
        if b20_info is not None:
            self.b20_info = b20_info

    @property
    def is_b20_token(self):
        """Gets the is_b20_token of this ResponseWrapperTokenSecurityB20Token.  # noqa: E501

        It describes whether the token is a B20 token.  \"1\" means true;  \"0\" means false;  # noqa: E501

        :return: The is_b20_token of this ResponseWrapperTokenSecurityB20Token.  # noqa: E501
        :rtype: str
        """
        return self._is_b20_token

    @is_b20_token.setter
    def is_b20_token(self, is_b20_token):
        """Sets the is_b20_token of this ResponseWrapperTokenSecurityB20Token.

        It describes whether the token is a B20 token.  \"1\" means true;  \"0\" means false;  # noqa: E501

        :param is_b20_token: The is_b20_token of this ResponseWrapperTokenSecurityB20Token.  # noqa: E501
        :type: str
        """

        self._is_b20_token = is_b20_token

    @property
    def b20_info(self):
        """Gets the b20_info of this ResponseWrapperTokenSecurityB20Token.  # noqa: E501


        :return: The b20_info of this ResponseWrapperTokenSecurityB20Token.  # noqa: E501
        :rtype: ResponseWrapperTokenSecurityB20TokenB20Info
        """
        return self._b20_info

    @b20_info.setter
    def b20_info(self, b20_info):
        """Sets the b20_info of this ResponseWrapperTokenSecurityB20Token.


        :param b20_info: The b20_info of this ResponseWrapperTokenSecurityB20Token.  # noqa: E501
        :type: ResponseWrapperTokenSecurityB20TokenB20Info
        """

        self._b20_info = b20_info

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ResponseWrapperTokenSecurityB20Token, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ResponseWrapperTokenSecurityB20Token):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
