# coding: utf-8

"""
    GoPlus Security API Document

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class SolanaAllowanceUpgrade(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'mint': 'str',
        'symbol': 'str',
        'decimals': 'int',
        'name': 'str',
        'new_allowances': 'list[NewAllowance]'
    }

    attribute_map = {
        'mint': 'mint',
        'symbol': 'symbol',
        'decimals': 'decimals',
        'name': 'name',
        'new_allowances': 'new_allowances'
    }

    def __init__(self, mint=None, symbol=None, decimals=None, name=None, new_allowances=None):  # noqa: E501
        """SolanaAllowanceUpgrade - a model defined in Swagger"""  # noqa: E501
        self._mint = None
        self._symbol = None
        self._decimals = None
        self._name = None
        self._new_allowances = None
        self.discriminator = None
        if mint is not None:
            self.mint = mint
        if symbol is not None:
            self.symbol = symbol
        if decimals is not None:
            self.decimals = decimals
        if name is not None:
            self.name = name
        if new_allowances is not None:
            self.new_allowances = new_allowances

    @property
    def mint(self):
        """Gets the mint of this SolanaAllowanceUpgrade.  # noqa: E501


        :return: The mint of this SolanaAllowanceUpgrade.  # noqa: E501
        :rtype: str
        """
        return self._mint

    @mint.setter
    def mint(self, mint):
        """Sets the mint of this SolanaAllowanceUpgrade.


        :param mint: The mint of this SolanaAllowanceUpgrade.  # noqa: E501
        :type: str
        """

        self._mint = mint

    @property
    def symbol(self):
        """Gets the symbol of this SolanaAllowanceUpgrade.  # noqa: E501


        :return: The symbol of this SolanaAllowanceUpgrade.  # noqa: E501
        :rtype: str
        """
        return self._symbol

    @symbol.setter
    def symbol(self, symbol):
        """Sets the symbol of this SolanaAllowanceUpgrade.


        :param symbol: The symbol of this SolanaAllowanceUpgrade.  # noqa: E501
        :type: str
        """

        self._symbol = symbol

    @property
    def decimals(self):
        """Gets the decimals of this SolanaAllowanceUpgrade.  # noqa: E501


        :return: The decimals of this SolanaAllowanceUpgrade.  # noqa: E501
        :rtype: int
        """
        return self._decimals

    @decimals.setter
    def decimals(self, decimals):
        """Sets the decimals of this SolanaAllowanceUpgrade.


        :param decimals: The decimals of this SolanaAllowanceUpgrade.  # noqa: E501
        :type: int
        """

        self._decimals = decimals

    @property
    def name(self):
        """Gets the name of this SolanaAllowanceUpgrade.  # noqa: E501


        :return: The name of this SolanaAllowanceUpgrade.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this SolanaAllowanceUpgrade.


        :param name: The name of this SolanaAllowanceUpgrade.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def new_allowances(self):
        """Gets the new_allowances of this SolanaAllowanceUpgrade.  # noqa: E501


        :return: The new_allowances of this SolanaAllowanceUpgrade.  # noqa: E501
        :rtype: list[NewAllowance]
        """
        return self._new_allowances

    @new_allowances.setter
    def new_allowances(self, new_allowances):
        """Sets the new_allowances of this SolanaAllowanceUpgrade.


        :param new_allowances: The new_allowances of this SolanaAllowanceUpgrade.  # noqa: E501
        :type: list[NewAllowance]
        """

        self._new_allowances = new_allowances

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(SolanaAllowanceUpgrade, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, SolanaAllowanceUpgrade):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
