# coding: utf-8

"""
    GoPlus Security API Document

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class SolanaPrerunTxRequest(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'encoded_transaction': 'str'
    }

    attribute_map = {
        'encoded_transaction': 'encoded_transaction'
    }

    def __init__(self, encoded_transaction=None):  # noqa: E501
        """SolanaPrerunTxRequest - a model defined in Swagger"""  # noqa: E501
        self._encoded_transaction = None
        self.discriminator = None
        if encoded_transaction is not None:
            self.encoded_transaction = encoded_transaction

    @property
    def encoded_transaction(self):
        """Gets the encoded_transaction of this SolanaPrerunTxRequest.  # noqa: E501


        :return: The encoded_transaction of this SolanaPrerunTxRequest.  # noqa: E501
        :rtype: str
        """
        return self._encoded_transaction

    @encoded_transaction.setter
    def encoded_transaction(self, encoded_transaction):
        """Sets the encoded_transaction of this SolanaPrerunTxRequest.


        :param encoded_transaction: The encoded_transaction of this SolanaPrerunTxRequest.  # noqa: E501
        :type: str
        """

        self._encoded_transaction = encoded_transaction

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(SolanaPrerunTxRequest, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, SolanaPrerunTxRequest):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
