# coding: utf-8

"""
    GoPlus Security API Document

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class SolanaTxSolChange(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'address': 'str',
        'post_lamports': 'str',
        'lamport_changes': 'str',
        'risky_address': 'int',
        'from_address': 'int',
        'pre_lamports': 'str'
    }

    attribute_map = {
        'address': 'address',
        'post_lamports': 'post_lamports',
        'lamport_changes': 'lamport_changes',
        'risky_address': 'risky_address',
        'from_address': 'from_address',
        'pre_lamports': 'pre_lamports'
    }

    def __init__(self, address=None, post_lamports=None, lamport_changes=None, risky_address=None, from_address=None, pre_lamports=None):  # noqa: E501
        """SolanaTxSolChange - a model defined in Swagger"""  # noqa: E501
        self._address = None
        self._post_lamports = None
        self._lamport_changes = None
        self._risky_address = None
        self._from_address = None
        self._pre_lamports = None
        self.discriminator = None
        if address is not None:
            self.address = address
        if post_lamports is not None:
            self.post_lamports = post_lamports
        if lamport_changes is not None:
            self.lamport_changes = lamport_changes
        if risky_address is not None:
            self.risky_address = risky_address
        if from_address is not None:
            self.from_address = from_address
        if pre_lamports is not None:
            self.pre_lamports = pre_lamports

    @property
    def address(self):
        """Gets the address of this SolanaTxSolChange.  # noqa: E501


        :return: The address of this SolanaTxSolChange.  # noqa: E501
        :rtype: str
        """
        return self._address

    @address.setter
    def address(self, address):
        """Sets the address of this SolanaTxSolChange.


        :param address: The address of this SolanaTxSolChange.  # noqa: E501
        :type: str
        """

        self._address = address

    @property
    def post_lamports(self):
        """Gets the post_lamports of this SolanaTxSolChange.  # noqa: E501


        :return: The post_lamports of this SolanaTxSolChange.  # noqa: E501
        :rtype: str
        """
        return self._post_lamports

    @post_lamports.setter
    def post_lamports(self, post_lamports):
        """Sets the post_lamports of this SolanaTxSolChange.


        :param post_lamports: The post_lamports of this SolanaTxSolChange.  # noqa: E501
        :type: str
        """

        self._post_lamports = post_lamports

    @property
    def lamport_changes(self):
        """Gets the lamport_changes of this SolanaTxSolChange.  # noqa: E501


        :return: The lamport_changes of this SolanaTxSolChange.  # noqa: E501
        :rtype: str
        """
        return self._lamport_changes

    @lamport_changes.setter
    def lamport_changes(self, lamport_changes):
        """Sets the lamport_changes of this SolanaTxSolChange.


        :param lamport_changes: The lamport_changes of this SolanaTxSolChange.  # noqa: E501
        :type: str
        """

        self._lamport_changes = lamport_changes

    @property
    def risky_address(self):
        """Gets the risky_address of this SolanaTxSolChange.  # noqa: E501


        :return: The risky_address of this SolanaTxSolChange.  # noqa: E501
        :rtype: int
        """
        return self._risky_address

    @risky_address.setter
    def risky_address(self, risky_address):
        """Sets the risky_address of this SolanaTxSolChange.


        :param risky_address: The risky_address of this SolanaTxSolChange.  # noqa: E501
        :type: int
        """

        self._risky_address = risky_address

    @property
    def from_address(self):
        """Gets the from_address of this SolanaTxSolChange.  # noqa: E501


        :return: The from_address of this SolanaTxSolChange.  # noqa: E501
        :rtype: int
        """
        return self._from_address

    @from_address.setter
    def from_address(self, from_address):
        """Sets the from_address of this SolanaTxSolChange.


        :param from_address: The from_address of this SolanaTxSolChange.  # noqa: E501
        :type: int
        """

        self._from_address = from_address

    @property
    def pre_lamports(self):
        """Gets the pre_lamports of this SolanaTxSolChange.  # noqa: E501


        :return: The pre_lamports of this SolanaTxSolChange.  # noqa: E501
        :rtype: str
        """
        return self._pre_lamports

    @pre_lamports.setter
    def pre_lamports(self, pre_lamports):
        """Sets the pre_lamports of this SolanaTxSolChange.


        :param pre_lamports: The pre_lamports of this SolanaTxSolChange.  # noqa: E501
        :type: str
        """

        self._pre_lamports = pre_lamports

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(SolanaTxSolChange, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, SolanaTxSolChange):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
