# coding: utf-8

"""
    GoPlus Security API Document

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class SolanaTxAssetChanges(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'nft_changes': 'list[SolanaTxAssetChange]',
        'token_changes': 'list[SolanaTxAssetChange]',
        'sol_changes': 'list[SolanaTxSolChange]'
    }

    attribute_map = {
        'nft_changes': 'nft_changes',
        'token_changes': 'token_changes',
        'sol_changes': 'sol_changes'
    }

    def __init__(self, nft_changes=None, token_changes=None, sol_changes=None):  # noqa: E501
        """SolanaTxAssetChanges - a model defined in Swagger"""  # noqa: E501
        self._nft_changes = None
        self._token_changes = None
        self._sol_changes = None
        self.discriminator = None
        if nft_changes is not None:
            self.nft_changes = nft_changes
        if token_changes is not None:
            self.token_changes = token_changes
        if sol_changes is not None:
            self.sol_changes = sol_changes

    @property
    def nft_changes(self):
        """Gets the nft_changes of this SolanaTxAssetChanges.  # noqa: E501


        :return: The nft_changes of this SolanaTxAssetChanges.  # noqa: E501
        :rtype: list[SolanaTxAssetChange]
        """
        return self._nft_changes

    @nft_changes.setter
    def nft_changes(self, nft_changes):
        """Sets the nft_changes of this SolanaTxAssetChanges.


        :param nft_changes: The nft_changes of this SolanaTxAssetChanges.  # noqa: E501
        :type: list[SolanaTxAssetChange]
        """

        self._nft_changes = nft_changes

    @property
    def token_changes(self):
        """Gets the token_changes of this SolanaTxAssetChanges.  # noqa: E501


        :return: The token_changes of this SolanaTxAssetChanges.  # noqa: E501
        :rtype: list[SolanaTxAssetChange]
        """
        return self._token_changes

    @token_changes.setter
    def token_changes(self, token_changes):
        """Sets the token_changes of this SolanaTxAssetChanges.


        :param token_changes: The token_changes of this SolanaTxAssetChanges.  # noqa: E501
        :type: list[SolanaTxAssetChange]
        """

        self._token_changes = token_changes

    @property
    def sol_changes(self):
        """Gets the sol_changes of this SolanaTxAssetChanges.  # noqa: E501


        :return: The sol_changes of this SolanaTxAssetChanges.  # noqa: E501
        :rtype: list[SolanaTxSolChange]
        """
        return self._sol_changes

    @sol_changes.setter
    def sol_changes(self, sol_changes):
        """Sets the sol_changes of this SolanaTxAssetChanges.


        :param sol_changes: The sol_changes of this SolanaTxAssetChanges.  # noqa: E501
        :type: list[SolanaTxSolChange]
        """

        self._sol_changes = sol_changes

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(SolanaTxAssetChanges, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, SolanaTxAssetChanges):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
