# coding: utf-8

"""
    GoPlus Security API Document

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class TransactionSecurityResponse(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'erc20_allowance_changes': 'list[AllowanceChange]',
        'erc20_balance_changes': 'list[ERC20BalanceChange]',
        'erc721_balance_changes': 'list[ERC721BalanceChange]',
        'flagged': 'list[Flag]',
        'is_revert': 'bool',
        'is_simulated': 'bool',
        'logs': 'list[LogEntry]',
        'native_balance_changes': 'list[NativeBalanceChange]',
        'revert_reason': 'str',
        'simulate_failed_reason': 'str',
        'suspicious_addresses': 'list[AddressInfo]',
        'suspicious_url': 'bool',
        'used_gas': 'int'
    }

    attribute_map = {
        'erc20_allowance_changes': 'erc20_allowance_changes',
        'erc20_balance_changes': 'erc20_balance_changes',
        'erc721_balance_changes': 'erc721_balance_changes',
        'flagged': 'flagged',
        'is_revert': 'is_revert',
        'is_simulated': 'is_simulated',
        'logs': 'logs',
        'native_balance_changes': 'native_balance_changes',
        'revert_reason': 'revert_reason',
        'simulate_failed_reason': 'simulate_failed_reason',
        'suspicious_addresses': 'suspicious_addresses',
        'suspicious_url': 'suspicious_url',
        'used_gas': 'used_gas'
    }

    def __init__(self, erc20_allowance_changes=None, erc20_balance_changes=None, erc721_balance_changes=None, flagged=None, is_revert=None, is_simulated=None, logs=None, native_balance_changes=None, revert_reason=None, simulate_failed_reason=None, suspicious_addresses=None, suspicious_url=None, used_gas=None):  # noqa: E501
        """TransactionSecurityResponse - a model defined in Swagger"""  # noqa: E501
        self._erc20_allowance_changes = None
        self._erc20_balance_changes = None
        self._erc721_balance_changes = None
        self._flagged = None
        self._is_revert = None
        self._is_simulated = None
        self._logs = None
        self._native_balance_changes = None
        self._revert_reason = None
        self._simulate_failed_reason = None
        self._suspicious_addresses = None
        self._suspicious_url = None
        self._used_gas = None
        self.discriminator = None
        if erc20_allowance_changes is not None:
            self.erc20_allowance_changes = erc20_allowance_changes
        if erc20_balance_changes is not None:
            self.erc20_balance_changes = erc20_balance_changes
        if erc721_balance_changes is not None:
            self.erc721_balance_changes = erc721_balance_changes
        if flagged is not None:
            self.flagged = flagged
        if is_revert is not None:
            self.is_revert = is_revert
        if is_simulated is not None:
            self.is_simulated = is_simulated
        if logs is not None:
            self.logs = logs
        if native_balance_changes is not None:
            self.native_balance_changes = native_balance_changes
        if revert_reason is not None:
            self.revert_reason = revert_reason
        if simulate_failed_reason is not None:
            self.simulate_failed_reason = simulate_failed_reason
        if suspicious_addresses is not None:
            self.suspicious_addresses = suspicious_addresses
        if suspicious_url is not None:
            self.suspicious_url = suspicious_url
        if used_gas is not None:
            self.used_gas = used_gas

    @property
    def erc20_allowance_changes(self):
        """Gets the erc20_allowance_changes of this TransactionSecurityResponse.  # noqa: E501


        :return: The erc20_allowance_changes of this TransactionSecurityResponse.  # noqa: E501
        :rtype: list[AllowanceChange]
        """
        return self._erc20_allowance_changes

    @erc20_allowance_changes.setter
    def erc20_allowance_changes(self, erc20_allowance_changes):
        """Sets the erc20_allowance_changes of this TransactionSecurityResponse.


        :param erc20_allowance_changes: The erc20_allowance_changes of this TransactionSecurityResponse.  # noqa: E501
        :type: list[AllowanceChange]
        """

        self._erc20_allowance_changes = erc20_allowance_changes

    @property
    def erc20_balance_changes(self):
        """Gets the erc20_balance_changes of this TransactionSecurityResponse.  # noqa: E501


        :return: The erc20_balance_changes of this TransactionSecurityResponse.  # noqa: E501
        :rtype: list[ERC20BalanceChange]
        """
        return self._erc20_balance_changes

    @erc20_balance_changes.setter
    def erc20_balance_changes(self, erc20_balance_changes):
        """Sets the erc20_balance_changes of this TransactionSecurityResponse.


        :param erc20_balance_changes: The erc20_balance_changes of this TransactionSecurityResponse.  # noqa: E501
        :type: list[ERC20BalanceChange]
        """

        self._erc20_balance_changes = erc20_balance_changes

    @property
    def erc721_balance_changes(self):
        """Gets the erc721_balance_changes of this TransactionSecurityResponse.  # noqa: E501


        :return: The erc721_balance_changes of this TransactionSecurityResponse.  # noqa: E501
        :rtype: list[ERC721BalanceChange]
        """
        return self._erc721_balance_changes

    @erc721_balance_changes.setter
    def erc721_balance_changes(self, erc721_balance_changes):
        """Sets the erc721_balance_changes of this TransactionSecurityResponse.


        :param erc721_balance_changes: The erc721_balance_changes of this TransactionSecurityResponse.  # noqa: E501
        :type: list[ERC721BalanceChange]
        """

        self._erc721_balance_changes = erc721_balance_changes

    @property
    def flagged(self):
        """Gets the flagged of this TransactionSecurityResponse.  # noqa: E501


        :return: The flagged of this TransactionSecurityResponse.  # noqa: E501
        :rtype: list[Flag]
        """
        return self._flagged

    @flagged.setter
    def flagged(self, flagged):
        """Sets the flagged of this TransactionSecurityResponse.


        :param flagged: The flagged of this TransactionSecurityResponse.  # noqa: E501
        :type: list[Flag]
        """

        self._flagged = flagged

    @property
    def is_revert(self):
        """Gets the is_revert of this TransactionSecurityResponse.  # noqa: E501


        :return: The is_revert of this TransactionSecurityResponse.  # noqa: E501
        :rtype: bool
        """
        return self._is_revert

    @is_revert.setter
    def is_revert(self, is_revert):
        """Sets the is_revert of this TransactionSecurityResponse.


        :param is_revert: The is_revert of this TransactionSecurityResponse.  # noqa: E501
        :type: bool
        """

        self._is_revert = is_revert

    @property
    def is_simulated(self):
        """Gets the is_simulated of this TransactionSecurityResponse.  # noqa: E501


        :return: The is_simulated of this TransactionSecurityResponse.  # noqa: E501
        :rtype: bool
        """
        return self._is_simulated

    @is_simulated.setter
    def is_simulated(self, is_simulated):
        """Sets the is_simulated of this TransactionSecurityResponse.


        :param is_simulated: The is_simulated of this TransactionSecurityResponse.  # noqa: E501
        :type: bool
        """

        self._is_simulated = is_simulated

    @property
    def logs(self):
        """Gets the logs of this TransactionSecurityResponse.  # noqa: E501


        :return: The logs of this TransactionSecurityResponse.  # noqa: E501
        :rtype: list[LogEntry]
        """
        return self._logs

    @logs.setter
    def logs(self, logs):
        """Sets the logs of this TransactionSecurityResponse.


        :param logs: The logs of this TransactionSecurityResponse.  # noqa: E501
        :type: list[LogEntry]
        """

        self._logs = logs

    @property
    def native_balance_changes(self):
        """Gets the native_balance_changes of this TransactionSecurityResponse.  # noqa: E501


        :return: The native_balance_changes of this TransactionSecurityResponse.  # noqa: E501
        :rtype: list[NativeBalanceChange]
        """
        return self._native_balance_changes

    @native_balance_changes.setter
    def native_balance_changes(self, native_balance_changes):
        """Sets the native_balance_changes of this TransactionSecurityResponse.


        :param native_balance_changes: The native_balance_changes of this TransactionSecurityResponse.  # noqa: E501
        :type: list[NativeBalanceChange]
        """

        self._native_balance_changes = native_balance_changes

    @property
    def revert_reason(self):
        """Gets the revert_reason of this TransactionSecurityResponse.  # noqa: E501


        :return: The revert_reason of this TransactionSecurityResponse.  # noqa: E501
        :rtype: str
        """
        return self._revert_reason

    @revert_reason.setter
    def revert_reason(self, revert_reason):
        """Sets the revert_reason of this TransactionSecurityResponse.


        :param revert_reason: The revert_reason of this TransactionSecurityResponse.  # noqa: E501
        :type: str
        """

        self._revert_reason = revert_reason

    @property
    def simulate_failed_reason(self):
        """Gets the simulate_failed_reason of this TransactionSecurityResponse.  # noqa: E501


        :return: The simulate_failed_reason of this TransactionSecurityResponse.  # noqa: E501
        :rtype: str
        """
        return self._simulate_failed_reason

    @simulate_failed_reason.setter
    def simulate_failed_reason(self, simulate_failed_reason):
        """Sets the simulate_failed_reason of this TransactionSecurityResponse.


        :param simulate_failed_reason: The simulate_failed_reason of this TransactionSecurityResponse.  # noqa: E501
        :type: str
        """

        self._simulate_failed_reason = simulate_failed_reason

    @property
    def suspicious_addresses(self):
        """Gets the suspicious_addresses of this TransactionSecurityResponse.  # noqa: E501


        :return: The suspicious_addresses of this TransactionSecurityResponse.  # noqa: E501
        :rtype: list[AddressInfo]
        """
        return self._suspicious_addresses

    @suspicious_addresses.setter
    def suspicious_addresses(self, suspicious_addresses):
        """Sets the suspicious_addresses of this TransactionSecurityResponse.


        :param suspicious_addresses: The suspicious_addresses of this TransactionSecurityResponse.  # noqa: E501
        :type: list[AddressInfo]
        """

        self._suspicious_addresses = suspicious_addresses

    @property
    def suspicious_url(self):
        """Gets the suspicious_url of this TransactionSecurityResponse.  # noqa: E501


        :return: The suspicious_url of this TransactionSecurityResponse.  # noqa: E501
        :rtype: bool
        """
        return self._suspicious_url

    @suspicious_url.setter
    def suspicious_url(self, suspicious_url):
        """Sets the suspicious_url of this TransactionSecurityResponse.


        :param suspicious_url: The suspicious_url of this TransactionSecurityResponse.  # noqa: E501
        :type: bool
        """

        self._suspicious_url = suspicious_url

    @property
    def used_gas(self):
        """Gets the used_gas of this TransactionSecurityResponse.  # noqa: E501


        :return: The used_gas of this TransactionSecurityResponse.  # noqa: E501
        :rtype: int
        """
        return self._used_gas

    @used_gas.setter
    def used_gas(self, used_gas):
        """Sets the used_gas of this TransactionSecurityResponse.


        :param used_gas: The used_gas of this TransactionSecurityResponse.  # noqa: E501
        :type: int
        """

        self._used_gas = used_gas

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(TransactionSecurityResponse, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, TransactionSecurityResponse):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
