# coding: utf-8

"""
    GoPlus Security API Document

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class TransactionSecurityRequest(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'access_list': 'list[AddressInfo]',
        'chain_id': 'str',
        'data': 'str',
        '_from': 'str',
        'gas_limit': 'str',
        'gas_price': 'str',
        'max_fee_per_gas': 'str',
        'max_priority_fee_per_gas': 'str',
        'nonce': 'str',
        'to': 'str',
        'url': 'str',
        'value': 'str'
    }

    attribute_map = {
        'access_list': 'access_list',
        'chain_id': 'chain_id',
        'data': 'data',
        '_from': 'from',
        'gas_limit': 'gas_limit',
        'gas_price': 'gas_price',
        'max_fee_per_gas': 'max_fee_per_gas',
        'max_priority_fee_per_gas': 'max_priority_fee_per_gas',
        'nonce': 'nonce',
        'to': 'to',
        'url': 'url',
        'value': 'value'
    }

    def __init__(self, access_list=None, chain_id=None, data=None, _from=None, gas_limit=None, gas_price=None, max_fee_per_gas=None, max_priority_fee_per_gas=None, nonce=None, to=None, url=None, value=None):  # noqa: E501
        """TransactionSecurityRequest - a model defined in Swagger"""  # noqa: E501
        self._access_list = None
        self._chain_id = None
        self._data = None
        self.__from = None
        self._gas_limit = None
        self._gas_price = None
        self._max_fee_per_gas = None
        self._max_priority_fee_per_gas = None
        self._nonce = None
        self._to = None
        self._url = None
        self._value = None
        self.discriminator = None
        if access_list is not None:
            self.access_list = access_list
        if chain_id is not None:
            self.chain_id = chain_id
        if data is not None:
            self.data = data
        if _from is not None:
            self._from = _from
        if gas_limit is not None:
            self.gas_limit = gas_limit
        if gas_price is not None:
            self.gas_price = gas_price
        if max_fee_per_gas is not None:
            self.max_fee_per_gas = max_fee_per_gas
        if max_priority_fee_per_gas is not None:
            self.max_priority_fee_per_gas = max_priority_fee_per_gas
        if nonce is not None:
            self.nonce = nonce
        if to is not None:
            self.to = to
        if url is not None:
            self.url = url
        if value is not None:
            self.value = value

    @property
    def access_list(self):
        """Gets the access_list of this TransactionSecurityRequest.  # noqa: E501


        :return: The access_list of this TransactionSecurityRequest.  # noqa: E501
        :rtype: list[AddressInfo]
        """
        return self._access_list

    @access_list.setter
    def access_list(self, access_list):
        """Sets the access_list of this TransactionSecurityRequest.


        :param access_list: The access_list of this TransactionSecurityRequest.  # noqa: E501
        :type: list[AddressInfo]
        """

        self._access_list = access_list

    @property
    def chain_id(self):
        """Gets the chain_id of this TransactionSecurityRequest.  # noqa: E501


        :return: The chain_id of this TransactionSecurityRequest.  # noqa: E501
        :rtype: str
        """
        return self._chain_id

    @chain_id.setter
    def chain_id(self, chain_id):
        """Sets the chain_id of this TransactionSecurityRequest.


        :param chain_id: The chain_id of this TransactionSecurityRequest.  # noqa: E501
        :type: str
        """

        self._chain_id = chain_id

    @property
    def data(self):
        """Gets the data of this TransactionSecurityRequest.  # noqa: E501


        :return: The data of this TransactionSecurityRequest.  # noqa: E501
        :rtype: str
        """
        return self._data

    @data.setter
    def data(self, data):
        """Sets the data of this TransactionSecurityRequest.


        :param data: The data of this TransactionSecurityRequest.  # noqa: E501
        :type: str
        """

        self._data = data

    @property
    def _from(self):
        """Gets the _from of this TransactionSecurityRequest.  # noqa: E501


        :return: The _from of this TransactionSecurityRequest.  # noqa: E501
        :rtype: str
        """
        return self.__from

    @_from.setter
    def _from(self, _from):
        """Sets the _from of this TransactionSecurityRequest.


        :param _from: The _from of this TransactionSecurityRequest.  # noqa: E501
        :type: str
        """

        self.__from = _from

    @property
    def gas_limit(self):
        """Gets the gas_limit of this TransactionSecurityRequest.  # noqa: E501


        :return: The gas_limit of this TransactionSecurityRequest.  # noqa: E501
        :rtype: str
        """
        return self._gas_limit

    @gas_limit.setter
    def gas_limit(self, gas_limit):
        """Sets the gas_limit of this TransactionSecurityRequest.


        :param gas_limit: The gas_limit of this TransactionSecurityRequest.  # noqa: E501
        :type: str
        """

        self._gas_limit = gas_limit

    @property
    def gas_price(self):
        """Gets the gas_price of this TransactionSecurityRequest.  # noqa: E501


        :return: The gas_price of this TransactionSecurityRequest.  # noqa: E501
        :rtype: str
        """
        return self._gas_price

    @gas_price.setter
    def gas_price(self, gas_price):
        """Sets the gas_price of this TransactionSecurityRequest.


        :param gas_price: The gas_price of this TransactionSecurityRequest.  # noqa: E501
        :type: str
        """

        self._gas_price = gas_price

    @property
    def max_fee_per_gas(self):
        """Gets the max_fee_per_gas of this TransactionSecurityRequest.  # noqa: E501


        :return: The max_fee_per_gas of this TransactionSecurityRequest.  # noqa: E501
        :rtype: str
        """
        return self._max_fee_per_gas

    @max_fee_per_gas.setter
    def max_fee_per_gas(self, max_fee_per_gas):
        """Sets the max_fee_per_gas of this TransactionSecurityRequest.


        :param max_fee_per_gas: The max_fee_per_gas of this TransactionSecurityRequest.  # noqa: E501
        :type: str
        """

        self._max_fee_per_gas = max_fee_per_gas

    @property
    def max_priority_fee_per_gas(self):
        """Gets the max_priority_fee_per_gas of this TransactionSecurityRequest.  # noqa: E501


        :return: The max_priority_fee_per_gas of this TransactionSecurityRequest.  # noqa: E501
        :rtype: str
        """
        return self._max_priority_fee_per_gas

    @max_priority_fee_per_gas.setter
    def max_priority_fee_per_gas(self, max_priority_fee_per_gas):
        """Sets the max_priority_fee_per_gas of this TransactionSecurityRequest.


        :param max_priority_fee_per_gas: The max_priority_fee_per_gas of this TransactionSecurityRequest.  # noqa: E501
        :type: str
        """

        self._max_priority_fee_per_gas = max_priority_fee_per_gas

    @property
    def nonce(self):
        """Gets the nonce of this TransactionSecurityRequest.  # noqa: E501


        :return: The nonce of this TransactionSecurityRequest.  # noqa: E501
        :rtype: str
        """
        return self._nonce

    @nonce.setter
    def nonce(self, nonce):
        """Sets the nonce of this TransactionSecurityRequest.


        :param nonce: The nonce of this TransactionSecurityRequest.  # noqa: E501
        :type: str
        """

        self._nonce = nonce

    @property
    def to(self):
        """Gets the to of this TransactionSecurityRequest.  # noqa: E501


        :return: The to of this TransactionSecurityRequest.  # noqa: E501
        :rtype: str
        """
        return self._to

    @to.setter
    def to(self, to):
        """Sets the to of this TransactionSecurityRequest.


        :param to: The to of this TransactionSecurityRequest.  # noqa: E501
        :type: str
        """

        self._to = to

    @property
    def url(self):
        """Gets the url of this TransactionSecurityRequest.  # noqa: E501


        :return: The url of this TransactionSecurityRequest.  # noqa: E501
        :rtype: str
        """
        return self._url

    @url.setter
    def url(self, url):
        """Sets the url of this TransactionSecurityRequest.


        :param url: The url of this TransactionSecurityRequest.  # noqa: E501
        :type: str
        """

        self._url = url

    @property
    def value(self):
        """Gets the value of this TransactionSecurityRequest.  # noqa: E501


        :return: The value of this TransactionSecurityRequest.  # noqa: E501
        :rtype: str
        """
        return self._value

    @value.setter
    def value(self, value):
        """Sets the value of this TransactionSecurityRequest.


        :param value: The value of this TransactionSecurityRequest.  # noqa: E501
        :type: str
        """

        self._value = value

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(TransactionSecurityRequest, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, TransactionSecurityRequest):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
